//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
// 
/// <remarks/>
namespace Jaeger.SAT.CFDI.Complemento.PersonasFisicasIntegrantes.V10 {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/pfic")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/pfic", IsNullable = false)]
    public partial class PFintegranteCoordinado {
        private string versionField;

        private string claveVehicularField;

        private string placaField;

        private string rFCPFField;

        public PFintegranteCoordinado() {
            this.versionField = "1.0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClaveVehicular {
            get {
                return this.claveVehicularField;
            }
            set {
                this.claveVehicularField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFCPF {
            get {
                return this.rFCPFField;
            }
            set {
                this.rFCPFField = value;
            }
        }
    }
}