//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.33440.
// 
/// <remarks/>
using System;
using System.IO;
using System.Reflection;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.XPath;
using System.Xml.Xsl;
using Jaeger.SAT.CFDI.Services;

namespace Jaeger.SAT.CFDI.Complemento.ImpuestosLocales.V10 {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/implocal")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/implocal", IsNullable = false)]
    public partial class ImpuestosLocales {
        [System.Xml.Serialization.XmlAttribute("schemaLocation", Namespace = "http://www.w3.org/2001/XMLSchema-instance")]
        public string XsiSchemaLocation;

        private ImpuestosLocalesRetencionesLocales[] retencionesLocalesField;

        private ImpuestosLocalesTrasladosLocales[] trasladosLocalesField;

        private string versionField;

        private decimal totaldeRetencionesField;

        private decimal totaldeTrasladosField;

        private static XmlSerializer objSerializer;

        public ImpuestosLocales() {
            this.versionField = "1.0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RetencionesLocales")]
        public ImpuestosLocalesRetencionesLocales[] RetencionesLocales {
            get {
                return this.retencionesLocalesField;
            }
            set {
                this.retencionesLocalesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrasladosLocales")]
        public ImpuestosLocalesTrasladosLocales[] TrasladosLocales {
            get {
                return this.trasladosLocalesField;
            }
            set {
                this.trasladosLocalesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotaldeRetenciones {
            get {
                return this.totaldeRetencionesField;
            }
            set {
                this.totaldeRetencionesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotaldeTraslados {
            get {
                return this.totaldeTrasladosField;
            }
            set {
                this.totaldeTrasladosField = value;
            }
        }

        #region Serializacion

        [XmlIgnore]
        public string CadenaOriginal {
            get {
                string outOriginalString;
                using (Stream manifestResourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream("Jaeger.Pagos10.xslt")) {
                    if (manifestResourceStream == null) {
                        outOriginalString = null;
                    } else {
                        XmlDocument xmlDocument = new XmlDocument();
                        xmlDocument.Load(manifestResourceStream);
                        using (StringWriter stringWriter = new StringWriter()) {
                            using (XmlTextWriter xmlTextWriter = new XmlTextWriter(stringWriter)) {
                                XslCompiledTransform xslCompiledTransform = new XslCompiledTransform();
                                xslCompiledTransform.Load(xmlDocument, null, new XmlResolverService());
                                xslCompiledTransform.Transform(new XPathDocument(new StringReader(this.Serialize())), null, xmlTextWriter);
                                outOriginalString = stringWriter.ToString();
                            }
                        }
                    }
                }
                return outOriginalString;
            }
        }

        private static XmlSerializer Serializer {
            get {
                if (ImpuestosLocales.objSerializer == null) {
                    ImpuestosLocales.objSerializer = (new XmlSerializerFactory()).CreateSerializer(typeof(ImpuestosLocales));
                }
                return ImpuestosLocales.objSerializer;
            }
        }

        public static bool Deserialize(string input, out ImpuestosLocales obj, out Exception exception) {
            bool flag;
            exception = null;
            obj = null;
            try {
                obj = ImpuestosLocales.Deserialize(input);
                flag = true;
            } catch (Exception exception1) {
                exception = exception1;
                flag = false;
            }
            return flag;
        }

        public static bool Deserialize(string input, out ImpuestosLocales obj) {
            Exception exception = new Exception();
            return ImpuestosLocales.Deserialize(input, out obj, out exception);
        }

        public static ImpuestosLocales Deserialize(string input) {
            StringReader objStringReader = new StringReader(input);
            ImpuestosLocales objPagos = (ImpuestosLocales)ImpuestosLocales.Serializer.Deserialize(XmlReader.Create(objStringReader));
            return objPagos;
        }

        public static ImpuestosLocales Deserialize(Stream s) {
            return (ImpuestosLocales)ImpuestosLocales.Serializer.Deserialize(s);
        }

        public virtual string Serialize() {
            string end;
            StreamReader streamReader = null;
            MemoryStream memoryStream = null;
            try {
                memoryStream = new MemoryStream();
                XmlWriterSettings xmlWriterSetting = new XmlWriterSettings() {
                    Encoding = Encoding.UTF8,
                    Indent = true
                };
                XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSetting);
                XmlSerializerNamespaces xmlSerializerNamespace = new XmlSerializerNamespaces();
                xmlSerializerNamespace.Add("pagos10", "http://www.sat.gob.mx/Pagos");
                xmlSerializerNamespace.Add("xsi", "http://www.w3.org/2001/XMLSchema-instance");
                this.XsiSchemaLocation = "http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd";
                ImpuestosLocales.Serializer.Serialize(xmlWriter, this, xmlSerializerNamespace);
                memoryStream.Seek((long)0, SeekOrigin.Begin);
                streamReader = new StreamReader(memoryStream, Encoding.UTF8);
                end = streamReader.ReadToEnd();
            } finally {
                if (streamReader != null) {
                    streamReader.Dispose();
                }
                if (memoryStream != null) {
                    memoryStream.Dispose();
                }
            }
            return end;
        }

        #endregion
    }
}

namespace Jaeger.SAT.CFDI.Complemento.ImpuestosLocales.V10 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/implocal")]
    public partial class ImpuestosLocalesRetencionesLocales {
        private string impLocRetenidoField;

        private decimal tasadeRetencionField;

        private decimal importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImpLocRetenido {
            get {
                return this.impLocRetenidoField;
            }
            set {
                this.impLocRetenidoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TasadeRetencion {
            get {
                return this.tasadeRetencionField;
            }
            set {
                this.tasadeRetencionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
}

namespace Jaeger.SAT.CFDI.Complemento.ImpuestosLocales.V10 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/implocal")]
    public partial class ImpuestosLocalesTrasladosLocales {
        private string impLocTrasladadoField;

        private decimal tasadeTrasladoField;

        private decimal importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ImpLocTrasladado {
            get {
                return this.impLocTrasladadoField;
            }
            set {
                this.impLocTrasladadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TasadeTraslado {
            get {
                return this.tasadeTrasladoField;
            }
            set {
                this.tasadeTrasladoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
}
