//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
// 

namespace Jaeger.SAT.CFDI.Complemento.TuristaPasajeroExtranjero.V10 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero", IsNullable = false)]
    public partial class TuristaPasajeroExtranjero {
        private TuristaPasajeroExtranjeroDatosTransito datosTransitoField;

        private string versionField;

        private System.DateTime fechadeTransitoField;

        private TuristaPasajeroExtranjeroTipoTransito tipoTransitoField;

        public TuristaPasajeroExtranjero() {
            this.versionField = "1.0";
        }

        /// <remarks/>
        public TuristaPasajeroExtranjeroDatosTransito datosTransito {
            get {
                return this.datosTransitoField;
            }
            set {
                this.datosTransitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime fechadeTransito {
            get {
                return this.fechadeTransitoField;
            }
            set {
                this.fechadeTransitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TuristaPasajeroExtranjeroTipoTransito tipoTransito {
            get {
                return this.tipoTransitoField;
            }
            set {
                this.tipoTransitoField = value;
            }
        }
    }
}

namespace Jaeger.SAT.CFDI.Complemento.TuristaPasajeroExtranjero.V10 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero")]
    public partial class TuristaPasajeroExtranjeroDatosTransito {
        private TuristaPasajeroExtranjeroDatosTransitoVia viaField;

        private string tipoIdField;

        private string numeroIdField;

        private string nacionalidadField;

        private string empresaTransporteField;

        private string idTransporteField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TuristaPasajeroExtranjeroDatosTransitoVia Via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoId {
            get {
                return this.tipoIdField;
            }
            set {
                this.tipoIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroId {
            get {
                return this.numeroIdField;
            }
            set {
                this.numeroIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmpresaTransporte {
            get {
                return this.empresaTransporteField;
            }
            set {
                this.empresaTransporteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdTransporte {
            get {
                return this.idTransporteField;
            }
            set {
                this.idTransporteField = value;
            }
        }
    }
}

namespace Jaeger.SAT.CFDI.Complemento.TuristaPasajeroExtranjero.V10 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero")]
    public enum TuristaPasajeroExtranjeroDatosTransitoVia {
        /// <remarks/>
        Aérea,

        /// <remarks/>
        Marítima,

        /// <remarks/>
        Terrestre,
    }
}

namespace Jaeger.SAT.CFDI.Complemento.TuristaPasajeroExtranjero.V10 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/TuristaPasajeroExtranjero")]
    public enum TuristaPasajeroExtranjeroTipoTransito {
        /// <remarks/>
        Arribo,

        /// <remarks/>
        Salida,
    }
}
