//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.33440.
// 

namespace Jaeger.SAT.CFDI.Complemento.EstadoCuentaCombustible.V12 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/EstadoDeCuentaCombustible12")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/EstadoDeCuentaCombustible12", IsNullable = false)]
    public partial class EstadoDeCuentaCombustible {
        private EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustible[] conceptosField;

        private string versionField;

        private string tipoOperacionField;

        private string numeroDeCuentaField;

        private decimal subTotalField;

        private decimal totalField;

        public EstadoDeCuentaCombustible() {
            this.versionField = "1.2";
            this.tipoOperacionField = "Tarjeta";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ConceptoEstadoDeCuentaCombustible", IsNullable = false)]
        public EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustible[] Conceptos {
            get {
                return this.conceptosField;
            }
            set {
                this.conceptosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroDeCuenta {
            get {
                return this.numeroDeCuentaField;
            }
            set {
                this.numeroDeCuentaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SubTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
}

namespace Jaeger.SAT.CFDI.Complemento.EstadoCuentaCombustible.V12 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/EstadoDeCuentaCombustible12")]
    public partial class EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustible {
        private EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTraslado[] trasladosField;

        private string identificadorField;

        private System.DateTime fechaField;

        private string rfcField;

        private string claveEstacionField;

        private decimal cantidadField;

        private c_ClaveTipoCombustible tipoCombustibleField;

        private string unidadField;

        private string nombreCombustibleField;

        private string folioOperacionField;

        private decimal valorUnitarioField;

        private decimal importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable = false)]
        public EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTraslado[] Traslados {
            get {
                return this.trasladosField;
            }
            set {
                this.trasladosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClaveEstacion {
            get {
                return this.claveEstacionField;
            }
            set {
                this.claveEstacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public c_ClaveTipoCombustible TipoCombustible {
            get {
                return this.tipoCombustibleField;
            }
            set {
                this.tipoCombustibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NombreCombustible {
            get {
                return this.nombreCombustibleField;
            }
            set {
                this.nombreCombustibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FolioOperacion {
            get {
                return this.folioOperacionField;
            }
            set {
                this.folioOperacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ValorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
}

namespace Jaeger.SAT.CFDI.Complemento.EstadoCuentaCombustible.V12 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/EstadoDeCuentaCombustible12")]
    public partial class EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTraslado {
        private EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTrasladoImpuesto impuestoField;

        private decimal tasaOCuotaField;

        private decimal importeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EstadoDeCuentaCombustibleConceptoEstadoDeCuentaCombustibleTrasladoImpuesto Impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TasaOCuota {
            get {
                return this.tasaOCuotaField;
            }
            set {
                this.tasaOCuotaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
}