//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.0.30319.33440.
// 
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using System.IO;
using System.Reflection;
using System.Xml.Xsl;
using System.Xml.XPath;
using System;
using Jaeger.SAT.CFDI.Services;

namespace Jaeger.SAT.CFDI.Complemento.LeyendasFiscales.V10 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/leyendasFiscales")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/leyendasFiscales", IsNullable = false)]
    public partial class LeyendasFiscales {
        [XmlAttribute("schemaLocation", Namespace = "http://www.w3.org/2001/XMLSchema-instance")]
        public string XsiSchemaLocation;

        private static XmlSerializer objSerializer;

        private LeyendasFiscalesLeyenda[] leyendaField;

        private string versionField;

        public LeyendasFiscales() {
            this.versionField = "1.0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Leyenda")]
        public LeyendasFiscalesLeyenda[] Leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }

        #region Serializacion

        [XmlIgnore]
        public string CadenaOriginal {
            get {
                string outOriginalString;
                using (Stream manifestResourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream("Jaeger.Pagos10.xslt")) {
                    if (manifestResourceStream == null) {
                        outOriginalString = null;
                    } else {
                        XmlDocument xmlDocument = new XmlDocument();
                        xmlDocument.Load(manifestResourceStream);
                        using (StringWriter stringWriter = new StringWriter()) {
                            using (XmlTextWriter xmlTextWriter = new XmlTextWriter(stringWriter)) {
                                XslCompiledTransform xslCompiledTransform = new XslCompiledTransform();
                                xslCompiledTransform.Load(xmlDocument, null, new XmlResolverService());
                                xslCompiledTransform.Transform(new XPathDocument(new StringReader(this.Serialize())), null, xmlTextWriter);
                                outOriginalString = stringWriter.ToString();
                            }
                        }
                    }
                }
                return outOriginalString;
            }
        }

        private static XmlSerializer Serializer {
            get {
                if (LeyendasFiscales.objSerializer == null) {
                    LeyendasFiscales.objSerializer = (new XmlSerializerFactory()).CreateSerializer(typeof(LeyendasFiscales));
                }
                return LeyendasFiscales.objSerializer;
            }
        }

        public static bool Deserialize(string input, out LeyendasFiscales obj, out Exception exception) {
            bool flag;
            exception = null;
            obj = null;
            try {
                obj = LeyendasFiscales.Deserialize(input);
                flag = true;
            } catch (Exception exception1) {
                exception = exception1;
                flag = false;
            }
            return flag;
        }

        public static bool Deserialize(string input, out LeyendasFiscales obj) {
            Exception exception = new Exception();
            return LeyendasFiscales.Deserialize(input, out obj, out exception);
        }

        public static LeyendasFiscales Deserialize(string input) {
            StringReader objStringReader = new StringReader(input);
            LeyendasFiscales objPagos = (LeyendasFiscales)LeyendasFiscales.Serializer.Deserialize(XmlReader.Create(objStringReader));
            return objPagos;
        }

        public static LeyendasFiscales Deserialize(Stream s) {
            return (LeyendasFiscales)LeyendasFiscales.Serializer.Deserialize(s);
        }

        public virtual string Serialize() {
            string end;
            StreamReader streamReader = null;
            MemoryStream memoryStream = null;
            try {
                memoryStream = new MemoryStream();
                XmlWriterSettings xmlWriterSetting = new XmlWriterSettings() {
                    Encoding = Encoding.UTF8,
                    Indent = true
                };
                XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSetting);
                XmlSerializerNamespaces xmlSerializerNamespace = new XmlSerializerNamespaces();
                xmlSerializerNamespace.Add("leyendasFisc:LeyendasFiscales", "http://www.sat.gob.mx/Pagos");
                xmlSerializerNamespace.Add("xsi", "http://www.w3.org/2001/XMLSchema-instance");
                this.XsiSchemaLocation = "http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd";
                LeyendasFiscales.Serializer.Serialize(xmlWriter, this, xmlSerializerNamespace);
                memoryStream.Seek((long)0, SeekOrigin.Begin);
                streamReader = new StreamReader(memoryStream, Encoding.UTF8);
                end = streamReader.ReadToEnd();
            } finally {
                if (streamReader != null) {
                    streamReader.Dispose();
                }
                if (memoryStream != null) {
                    memoryStream.Dispose();
                }
            }
            return end;
        }

        #endregion
    }
}

namespace Jaeger.SAT.CFDI.Complemento.LeyendasFiscales.V10 {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/leyendasFiscales")]
    public partial class LeyendasFiscalesLeyenda {
        private string disposicionFiscalField;

        private string normaField;

        private string textoLeyendaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disposicionFiscal {
            get {
                return this.disposicionFiscalField;
            }
            set {
                this.disposicionFiscalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string norma {
            get {
                return this.normaField;
            }
            set {
                this.normaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string textoLeyenda {
            get {
                return this.textoLeyendaField;
            }
            set {
                this.textoLeyendaField = value;
            }
        }
    }
}